version: '3.7'

networks:
  minio_network:

services:  
  minio:
    container_name: minio
    image: minio/minio:latest
    volumes:
      - ./data:/data
    ports:
      - "${MINIO_PORT}:9000"
    networks:
      - minio_network
    restart: always      
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
      #MINIO_REGION_NAME: home
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-console:
    container_name: minio-console
    image: minio/console:latest
    ports:
      - "${MINIO_CONSOLE_PORT}:9090"
    networks:
      - minio_network
    command: server
    restart: always
    environment:
      #- CONSOLE_PBKDF_PASSPHRASE=console123
      #- CONSOLE_PBKDF_SALT=console123
      - CONSOLE_MINIO_SERVER=http://minio:9000
    depends_on:
      - minio

  minio-client:
    container_name: minio-client
    image: minio/mc:latest
    volumes:
      - ./config:/root/.mc
    depends_on:
      - minio
    networks:
      - minio_network    
    restart: always
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm minio;
      /usr/bin/mc config host add --quiet --api s3v4 minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};    
      sleep infinity;
      "

